export interface film {
    characters: String[],
    created: String,
    director: String,
    edited: String,
    Stringepisode_id: Number,
    opening_crawl: String,
    planets: String[],
    producer: String,
    release_date: String,
    species: String[],
    starships: String[],
    title: String,
    url: String,
    vehicles: String[],
    episode_id: Number,
    favorite? : Boolean,
}
